version: 0.2
 
phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - apt-get install -y unzip

  build:
    commands:
      - echo Build started on `date`
      - zip ./index.jade 
   
artifacts:
  type: 
  files:
    - index.jade
    - scripts/install_dependencies
    - scripts/start_server
    - back.jpg
    - app.js
    - package.json
